### ISSUE TITLE
Frequrntly updating text in ToolStrip is a major performance hit

### ISSUE THREAD

**Issue by koolkdev** [CarJem/ManiacEditor-GenerationsEdition#3]
In GraphicPanel_OnMouseMove, there is a code that updates some text labels in the bottom status bar. ToolStrip isn't an appropriate container to be frequently updated, you should use StatusStrip instead. 
Using ToolStrip causes the program to hog the CPU just by moving the mouse.

**Comment by CarJem** [comment]
Thanks for the information, I will work on fixing that ASAP! Oh, and welcome back by the way!

**Comment by CarJem** [comment]
Fixed in latest commit, fc2f49d. Closing.
