### ISSUE TITLE
Crash on Windows 7 when opening Entities Toolbar

### ISSUE THREAD

**Issue by OtherworldBob** [CarJem/ManiacEditor-GenerationsEdition#4]
## Steps To Reproduce
1. Open a Data Folder from Mania Plus or plain old Mania
2. Select and Load a Scene (GHZ1 will do)
3. Click the red Entities button to open the control on the right - Maniac will crash before the control opens.

I'm running Windows 7 if it makes a difference.
Occurs on version 1.0.0.81

**Comment by OtherworldBob** [comment]
Combined with the change here: https://github.com/OtherworldBob/RSDK-Reverse/commit/245ff407064ba82a1c4356c214b6b5c104d66d22
Seems to fix the crash I get when opening the Entities pane.
Anyone able to confirm, or see any regressions? Especially on Windows 8+, which I am unable to test.

**Comment by CarJem** [comment]
@OtherworldBob Nice work Pal, I removed the unneeded Reference of Areo2 from all other tools as well, that should fix the problem. We will see after I get feedback from the latest build

**Comment by OtherworldBob** [comment]
Just downloaded and run 1.0.0.93, opens GHZ1 and the Entities pane without issue on my machine.

**Comment by CarJem** [comment]
Ok, I tested and asked about this issue further and confirmed that I may closed it after extensive and careful testing.
