### ISSUE TITLE
Windows 10 Home Edition - Not Executing

### ISSUE THREAD

**Issue by MrMadMothy** [CarJem/ManiacEditor-GenerationsEdition#8]
I'm having trouble managing to start the ManiacEditor.exe on my Windows 10 Home PC. I double clicked, waited and nothing has shown, I tried in multiple compatibility settings, enabled administrative support, tried loading it up on the C Drive and Desktop but to no avail, though this is not the case with ManiaPal.exe, as that loads up almost instantly.

**Comment by CarJem** [comment]
Merged to Issue #16
